services:
  db:
    image: postgres:15
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=skymirror
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: