export const COURSE_CATEGORIES = [
  'Programming',
  'Web Development',
  'Mobile Development',
  'Data Science',
  'Artificial Intelligence',
  'Machine Learning',
  'Cybersecurity',
  'Cloud Computing',
  'DevOps',
  'Blockchain',
  'Game Development',
  'UI/UX Design',
  'Graphic Design',
  'Digital Marketing',
  'Business',
  'Finance',
  'Entrepreneurship',
  'Personal Development',
  'Health & Fitness',
  'Music',
  'Photography',
  'Language Learning',
  'Test Prep',
  'Teaching & Academics',
  'Lifestyle',
  'Other'
] as const;

export const LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Chinese',
  'Japanese',
  'Korean',
  'Russian',
  'Portuguese',
  'Arabic',
  'Hindi',
  'Bengali',
  'Punjabi',
  'Tamil',
  'Telugu',
  'Marathi',
  'Gujarati',
  'Urdu',
  'Other'
] as const;
